"""empty message

Revision ID: 10d24914d06b
Revises: 16e73e485b7e
Create Date: 2020-08-26 19:51:27.043174

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10d24914d06b'
down_revision = '16e73e485b7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', mysql.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
