"""empty message

Revision ID: 16e73e485b7e
Revises: 
Create Date: 2020-08-26 08:33:51.958413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16e73e485b7e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('wid', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('lasttime', sa.DateTime(), nullable=True),
    sa.Column('thumb', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('wid'),
    sa.UniqueConstraint('wid')
    )
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('gender', sa.Enum('男', '女', '保密'), nullable=True),
    sa.Column('phone', sa.String(length=16), nullable=False),
    sa.Column('city', sa.String(length=16), nullable=True),
    sa.Column('photo', sa.String(length=128), nullable=True),
    sa.Column('hobbit', sa.String(length=20), nullable=True),
    sa.Column('des', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uid'),
    sa.UniqueConstraint('phone'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('blog')
    # ### end Alembic commands ###
