"""empty message

Revision ID: 67d81ad36169
Revises: c62ebee59b49
Create Date: 2020-08-28 11:39:41.797660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67d81ad36169'
down_revision = 'c62ebee59b49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follow',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('fid', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('uid', 'fid')
    )
    op.add_column('users', sa.Column('fans', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('follow', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'follow')
    op.drop_column('users', 'fans')
    op.drop_table('follow')
    # ### end Alembic commands ###
